# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

distance_point_to_line_cpp <- function(x_point, y_point, x_line, y_line) {
    .Call(`_roverlap_distance_point_to_line_cpp`, x_point, y_point, x_line, y_line)
}

point_in_polygon_cpp <- function(x_point, y_point, x_polygon, y_polygon, max_x_polygon, min_x_polygon, max_y_polygon, min_y_polygon) {
    .Call(`_roverlap_point_in_polygon_cpp`, x_point, y_point, x_polygon, y_polygon, max_x_polygon, min_x_polygon, max_y_polygon, min_y_polygon)
}

npoints_in_polygon_cpp <- function(x_points, y_points, x_polygon, y_polygon, max_x_polygon, min_x_polygon, max_y_polygon, min_y_polygon) {
    .Call(`_roverlap_npoints_in_polygon_cpp`, x_points, y_points, x_polygon, y_polygon, max_x_polygon, min_x_polygon, max_y_polygon, min_y_polygon)
}

point_overlap_line_cpp <- function(x_point, y_point, distance, x_line, y_line) {
    .Call(`_roverlap_point_overlap_line_cpp`, x_point, y_point, distance, x_line, y_line)
}

npoints_overlap_line_cpp <- function(x_points, y_points, distance, x_line, y_line) {
    .Call(`_roverlap_npoints_overlap_line_cpp`, x_points, y_points, distance, x_line, y_line)
}

