# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

distance_point_to_line_impl <- function(x_point, y_point, x_line, y_line) {
    .Call(`_roverlap_distance_point_to_line_impl`, x_point, y_point, x_line, y_line)
}

